M48
; DRILL file {KiCad 9.0.4} date 2025-09-18T08:56:35-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-18T08:56:35-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.250
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T2C0.300
%
G90
G05
T1
X132.182Y-73.627
T2
X135.877Y-70.692
M30
