M48
; DRILL file {KiCad 9.0.4} date 2025-10-03T15:45:51-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-03T15:45:51-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.250
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T2C0.300
%
G90
G05
T1
X132.182Y-73.914
T2
X135.534Y-71.12
M30
